version: '2'
services:
    dtotest-app:
        image: dtotest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://dtotest-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=dtotest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dtotest-mongodb:
        extends:
            file: mongodb.yml
            service: dtotest-mongodb
